### ISSUE TITLE
Titanium Alloy

### ISSUE THREAD

**Issue by roldanunne** [caffeinalab/gcm#9]
Hi, I was happy to find this module.
Can you help me how to used this in Titanium Alloy?

**Comment by kopiro** [comment]
Watch the README.
What isn't clear?

**Comment by roldanunne** [comment]
Thanks kopiro. 
My problem is, I don't know how to use this in my current apps. I'm using Appcelerator Studio.

**Comment by kopiro** [comment]
@roldanunne first of all, did you install it?

**Comment by roldanunne** [comment]
Yes, I installed it tru Help->Install Mobile Module

**Comment by kopiro** [comment]
@roldanunne Perfecto.
Now, using the Google Developer Console, obtain a GCM sender ID.

Then, in your alloy.js or index.js (when you want to register your device), call GCM.registerForPushNotifications passing the sender ID, a callback to invoke when a push notification incomes and a success callback that give you the device token. (there is an example in the Readme).

Now that you have a device token, you can send it to your Push notification server to store it or to Parse.

**Comment by roldanunne** [comment]
@kopiro  Thank you. I will try to apply this info. I'll get back to you if I make it or not... thanks

**Comment by roldanunne** [comment]
@kopiro Do I need to declare this tiapp.xml?

**Comment by roldanunne** [comment]
@kopiro If yes, why I cannot add on it?

**Comment by roysinclair** [comment]
@roldanunne 

Figure since i am using this module and it was a total life save for me, i will try to give back and answer the question.

In the tiapp.xml file close to the bottom is <modules> you will insert 
<module platform="android">it.caffeina.gcm</module>
before the closing tag  </modules>

Then in you alloy.js or index.js my preference is alloy.js.

Add the code from the Readme heading --> Register for Push notifications
IF you want to run a quick test change Ti.API.log('Notifications: device token is ' + e.deviceToken); to  alert('Notifications: device token is ' + e.deviceToken);

Make sure that gcm.unregisterForPushNotifications(); IS NOT included in alloy.js as in not directly under the code from the Readme --> Register for Push notifications

Create a function to be called to run gcm.unregisterForPushNotifications();
e.g. 

function unregisterPush(){
gcm.unregisterForPushNotifications();
}

I have included a pastebin link for what i would add into alloy.js
http://pastebin.com/UEzeMU35

**Comment by kopiro** [comment]
@roysinclair Thank you for the clear explanation!

I suggest you both ( @roldanunne  ) to try Trimethyl, our framework: https://github.com/caffeinalab/trimethyl.

You can abstract the notification mechanism with iOS/Android using the same module:
http://caffeinalab.github.io/trimethyl/module-notifications.html

Just use:

```
var Notifications = T('notifications');
Notifications.subscribe();
```

**Comment by roldanunne** [comment]
@kopiro Thank you for explanation and for your new framework. 
I'm still having a problem. I put the the code in the alloy.js

var gcm = require('it.caffeina.gcm');

```
gcm.registerForPushNotifications({

        // you take this from the Google Developer Console, is the project ID
        senderId: 'MysenderID',

        // The callback to invoke when a notification arrives.
        callback: function(e) {
            // Here you have the payload `e` of the upcoming notification
            // Handle how you want.
            alert('Notifications CallBack : ' + JSON.stringify(e));
        },

        // The callback invoked when you have the device token.
        success: function(e) {
            // share image
            alert('Notifications Succes : ' +  e.deviceToken);
        },

        // The callback invoked on some errors.
        error: function(err) {
            alert('Notifications Error : ' +  err);
            Ti.API.error('Notifications: Retrieve device token failed', err);
        }
    }); 
```

but still I'm not receiving notification.
after sending in the server, I have this response  :
{"multicast_id":6476039633741383150,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1465213386880439%7cc98abcf9fd7ecd"}]}

**Comment by kopiro** [comment]
Kill the app.
Does the notification appears?

**Comment by roldanunne** [comment]
Nothing... I try to restart the phone, now I see the app running in service, so I'm expecting that I will recieve the notification, but still nothings happen.

**Comment by kopiro** [comment]
Could you post a `logcat` of your app?
